/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package code;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class App {
    private static final Logger logger = LoggerFactory.getLogger(App.class);

    public String str = "Hello";

    public String getGreeting(String s) {
        logger.info(s);
        return "Hello";
    }

    public static void main(String[] args) {
        logger.info("Logger");
    }
}
