/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package code

import kotlin.test.Test
import kotlin.test.assertNotNull

class HelloTest {
    @Test fun testAppHasAGreeting() {
        val classUnderTest = Hello()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }
}
