/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package code

class Hello {
    val greeting: String
        get() {
            return "Hello world."
        }
    val items = listOf<String>("apple", "banana", "application", "alpha")

}